registering,login, all processes connected with users stuff
szmo/price_monitor pull request #8
Opened 2017-11-12 12:52 UTC by szmo

https://trello.com/c/CrhmUmmt/20-dodanie-kont-u%C5%BCytkownik%C3%B3w

2017-11-13 11:21 UTC, evemorgen commented
There should be ```sign up``` button next to ```log in``` button
<img width="1280" alt="screen shot 2017-11-13 at 12 18 27" src="https://user-images.githubusercontent.com/7932772/32723247-1575f588-c86d-11e7-9e53-2e06165a6aa9.png">

2017-11-13 11:22 UTC, evemorgen commented
Kodus for being ```rwd``` out of the box :D
<img width="727" alt="screen shot 2017-11-13 at 12 22 12" src="https://user-images.githubusercontent.com/7932772/32723305-4ec8090c-c86d-11e7-8700-6b814b1b90eb.png">

2017-11-13 11:25 UTC, evemorgen commented
```sign in``` button overlays ```confirm password``` text box, I guess there should be ```margin-top``` or sth similar
<img width="273" alt="screen shot 2017-11-13 at 12 23 27" src="https://user-images.githubusercontent.com/7932772/32723412-aa1a973e-c86d-11e7-8113-785781aae322.png">

2017-11-13 12:47 UTC, evemorgen requested changes

2017-11-13 12:47 UTC, evemorgen commented on rails_app/db/schema.rb
> +    t.string "login", default: "", null: false
Not sure if default value of empty string is suitable for login, lol. Besides that defining default value for ```not null``` is pointless. Same applies to rest of stuff defined in similar fashion.

2017-11-13 12:47 UTC, evemorgen commented on rails_app/config/initializers/devise.rb
> +# Use this hook to configure devise mailer, warden hooks and so forth.
This file is totally unreadable. Comments are over 93% of this file (sic!)

2017-11-13 12:47 UTC, evemorgen commented on rails_app/app/models/user.rb
> +  devise :database_authenticatable, :registerable,
maybe it is worth considering to add ```Timeoutable```

2017-11-13 12:47 UTC, evemorgen commented on rails_app/app/views/layouts/_header.html.haml
>          = link_to 'Price monitor', root_url, class: 'navbar-brand'
I guess we should add here our cool new logo:
<img width="426" alt="screen shot 2017-11-13 at 13 38 22" src="https://user-images.githubusercontent.com/7932772/32726342-f6128bfa-c878-11e7-8514-03297a1a774f.png">

2017-11-13 19:14 UTC, szmo commented on rails_app/config/initializers/devise.rb
> +# Use this hook to configure devise mailer, warden hooks and so forth.
i would rather left is in this state

2017-11-13 23:13 UTC, evemorgen commented on rails_app/config/initializers/devise.rb
> +# Use this hook to configure devise mailer, warden hooks and so forth.
ok

2017-11-13 23:14 UTC, evemorgen commented on rails_app/app/models/user.rb
> +  devise :database_authenticatable, :registerable,
not worth spending time on this now

2017-11-13 23:21 UTC, evemorgen approved these changes

2017-11-15 20:48 UTC, evemorgen commented
ok

2017-11-15 20:57 UTC, merged